upload_max_filesize = 10G
post_max_size = 10G
max_execution_time = 300
max_input_time = 300
memory_limit = 512M
session.auto_start = 0
session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
