server {
    listen 80;
    server_name pan.xxclub.me;

    root /var/www/html/pan;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "upload_max_filesize=10G\npost_max_size=10G\nmax_execution_time=300\nmax_input_time=300";
    }

    # 限制上传文件大小
    client_max_body_size 10G;
    client_body_timeout 300s;
    client_header_timeout 300s;
}